### ISSUE TITLE
WGCNA

### ISSUE THREAD

**Issue by tu12dou** [benben-miao/TOmicsVis#3]
你好，包里面的WGCNA算法适用于基因芯片数据吗？

**Comment by benben-miao** [comment]
> 你好，包里面的WGCNA算法适用于基因芯片数据吗？

你好，可以应用于基因芯片的表达数据的。具体案例和视频今天已经上传到哔哩哔哩：【6. TOmicsVis高级分析及可视化-哔哩哔哩】 https://b23.tv/YRnNA6k，视频中包含在Rstudio中的演示！
