### ISSUE TITLE
How to remove gene names when using circos_heatmap funnction？

### ISSUE THREAD

**Issue by yunbokai** [benben-miao/TOmicsVis#4]
Hi, Thanks for your great package!

I want to use circos_heatmap fuction. However, my data have too much genes and I don't want to show them or I just want show some of them. What should I do?

Best wishes.

**Comment by benben-miao** [comment]
Hello, thank you for your feedback.

We have released TOmicsVis v1.2.4 to github channel (https://github.com/benben-miao/TOmicsVis/) (`devtools::install_github ("benben-miao/TOmicsVis"`) today to promptly address your aforementioned suggestions. In this version, `circos_heatmap(rowname_show="none")` can control whether gene names are displayed and their position. If necessary , hiding a specific gene can be achieved by altering the input data. We will use an example to demonstrate that `rownames(data)[1] <- ""` (Figure 1).
![Hiding a specific gene.](https://s1.ax1x.com/2023/07/26/pCjQVpt.png)

**Comment by yunbokai** [comment]
I will try it, thanks again.
