### ISSUE TITLE
How to prepare the gene_go_kegg.txt file

### ISSUE THREAD

**Issue by zhangwenda0518** [benben-miao/TOmicsVis#5]
### 
    Hello, author, thank you for developing such a powerful program. I want to consult the nonparametric transcriptome or the nonparametric genome of non-model plants. Can you recommend me how to get the annotation results of go and kegg, and quickly get the file in the format of gene_go_kegg.txt?
      thanks！

**Comment by benben-miao** [comment]
Hello, 

If it is a transcriptome with a reference genome, the GO and KEGG annotation tables of genes come from the annotation of the genome. In the case of a transcriptome without a reference genome, the GO and KEGG annotation results of genes need to be blast to the GO and KEGG databases to obtain annotation information, and then organize the table into the format required by TOmicsVis. Note that when a gene contains multiple GO and KEGG items, it is separated by a semicolon ";" in a cell, and unannotated results are represented by NA..

Genes | biological_process | cellular_component | molecular_function | kegg_pathway
